const path = {
  all: "*",
  home: "/",
  modals: "/modals/",
  confirmator: "/confirmator/:confirmatorId/",
  confirmed: "/confirmed/:confirmatorId/",
  avaliable: "/avaliable/",
  caller: "/caller/:callerId/",
  superAdmin: "/superAdmin/",
  admin: "/admin/:adminId/",
  users: "users/",
  groups: "groups/",
  courses: "courses/",
  actions: "actions/",
  manager: "/manager/:managerId/",
  consultations: "consultations/",
  planning: "planning/",
  crm: "searchcrm/",
  pageCrm: "/searchcrm/",
  statistics: "/statistics/",
  postpone: "/confirmator/23/",
  currentManagers: "/currentManagers/",
  currentManagersList: "/currentManagersList/",
  currentManagersTable: "/currentManagersTable/",
  history: "/history/",
  authorization: "auth/",
  ik: "ik/",
};
export default path;
