const path = {
  all: '*',
  home: '/',
  avaliableTable: 'available/',
  modals: '/modals/',
  confirmator: '/confirmator/:confirmatorId/',
  confirmed: '/confirmed/:confirmatorId/',
  avaliable: '/avaliable/',
  caller: '/caller/:callerId/',
  superAdmin: '/admin/',
  admin: '/admin/:adminId/',
  users: 'users/',
  groups: 'groups/',
  appointments: 'appointments/',
  courses: 'courses/',
  actions: 'actions/',
  manager: '/manager/:managerId/',
  consultations: 'consultations/',
  planning: 'planning/',
  crm: 'searchcrm/',
  pageCrm: '/searchcrm/',
  statistics: '/statistics/',
  postpone: '/confirmator/23/',
  currentManagers: '/currentManagers/',
  currentManagersList: '/currentManagersList/',
  currentManagersTable: '/currentManagersTable/',
  history: '/history/',
  authorization: 'auth/',
  ik: 'ik/',
  teacher: '/teacher/'
};
export default path;
