const path = {
  all: '*',
  lessons: 'lessons',
  MyLesson: 'myLesson/',
  home: '/',
  info: 'info/',
  spreadsheet: 'spreadsheet',
  mySubgroups: 'mySubgroups/',
  resetPassword: '/resetPassword/:token',
  avaliableTable: 'available',
  modals: '/modals/',
  confirmator: '/confirmator/:confirmatorId/',
  confirmed: '/confirmed/:confirmatorId/',
  avaliable: '/avaliable/',
  caller: '/caller/:callerId/',
  superAdmin: '/admin/',
  admin: '/admin/:adminId/',
  users: 'users',
  groups: 'groups/',
  appointments: 'appointments',
  MIC: '/mic/',
  mentors: 'mentors', // for mentors list for MICs
  courses: 'courses',
  addMySubgroup: 'addMySubgroup/',
  editMySubgroup: 'editMySubgrop/',
  actions: 'actions/',
  manager: '/manager/:managerId/',
  consultations: 'consultations/',
  planning: 'planning/',
  crm: 'searchcrm/',
  pageCrm: '/searchcrm/',
  statistics: 'statistics/',
  postpone: '/confirmator/23/',
  currentManagers: '/currentManagers/',
  currentManagersList: '/currentManagersList/',
  currentManagersTable: '/currentManagersTable/',
  history: '/history/',
  authorization: 'auth/',
  ik: 'ik/',
  teacher: '/teacher/',
  subgroups: 'subgroups',
  replacements: 'replacements',
  //QC manager
  QCManager: '/qc-manager/',
  report: 'report/'
};
export default path;
